#
# Copyright (c) 2022 Airbyte, Inc., all rights reserved.
#

#        "source_defined_cursor" : true,
#        "default_cursor_field" : ["created_at"]


import json
import os
from datetime import datetime
from typing import Dict, Generator

from airbyte_cdk.logger import AirbyteLogger
from airbyte_cdk.models import (
    AirbyteCatalog,
    AirbyteConnectionStatus,
    AirbyteMessage,
    AirbyteRecordMessage,
    AirbyteStateMessage,
    AirbyteStream,
    ConfiguredAirbyteCatalog,
    Status,
    Type,
)
from airbyte_cdk.sources import Source
from jsonref import requests


class Peggler:
    base_uri: str = "https://peggle-data-collector.herokuapp.com/games/search"

    def get_games(self, limit: int = -1):  # , logger: AirbyteLogger
        params = {"limit": limit}
        r = requests.get(url=self.base_uri, params=params)
        return r.json()


class SourceTesting(Source):
    def check(self, logger: AirbyteLogger, config: json) -> AirbyteConnectionStatus:
        """
        Tests if the input configuration can be used to successfully connect to the integration
            e.g: if a provided Stripe API token can be used to connect to the Stripe API.

        :param logger: Logging object to display debug/info/error to the logs
            (logs will not be accessible via airbyte UI if they are not passed to this logger)
        :param config: Json object containing the configuration of this source, content of this json is as specified in
        the properties of the spec.yaml file

        :return: AirbyteConnectionStatus indicating a Success or Failure
        """
        logger.info("connection status succeded")
        return AirbyteConnectionStatus(status=Status.SUCCEEDED)

    def discover(self, logger: AirbyteLogger, config: json) -> AirbyteCatalog:
        """
        Returns an AirbyteCatalog representing the available streams and fields in this integration.
        For example, given valid credentials to a Postgres database,
        returns an Airbyte catalog where each postgres table is a stream, and each table column is a field.

        :param logger: Logging object to display debug/info/error to the logs
            (logs will not be accessible via airbyte UI if they are not passed to this logger)
        :param config: Json object containing the configuration of this source, content of this json is as specified in
        the properties of the spec.yaml file

        :return: AirbyteCatalog is an object describing a list of all available streams in this source.
            A stream is an AirbyteStream object that includes:
            - its stream name (or table name in the case of Postgres)
            - json_schema providing the specifications of expected schema for this stream (a list of columns described
            by their names and types)
        """
        streams = []
        # data_path = pkg_resources.resource_filename("source_testing", "schemas/")
        dirname = os.path.dirname(os.path.realpath(__file__))
        spec_path = os.path.join(dirname, "test_catalog.json")
        catalog = read_json(spec_path)
        streams.append(
            AirbyteStream(
                name="content",
                source_defined_cursor=True,
                default_cursor_field=["created_at"],
                json_schema=catalog,
                supported_sync_modes=["full_refresh", "incremental"],
            )
        )
        logger.info(f"created a catalog on 'content' stream: {catalog}")
        # for file in os.listdir(data_path): if not file.endswith(".json"): continue with open(os.path.join(data_path, file)) as f: try:
        # schema = json.load(f) streams.append(AirbyteStream(name=file.replace(".json", ""), supported_sync_modes=["full_refresh"],
        # json_schema=schema)) except JSONDecodeError as e: raise Exception(f"Unable to parse {file}: {e}")

        return AirbyteCatalog(streams=streams)

    def read(
        self, logger: AirbyteLogger, config: json, catalog: ConfiguredAirbyteCatalog, state: Dict[str, any]
    ) -> Generator[AirbyteMessage, None, None]:
        """
        Returns a generator of the AirbyteMessages generated by reading the source with the given configuration,
        catalog, and state.

        :param logger: Logging object to display debug/info/error to the logs
            (logs will not be accessible via airbyte UI if they are not passed to this logger)
        :param config: Json object containing the configuration of this source, content of this json is as specified in
            the properties of the spec.yaml file
        :param catalog: The input catalog is a ConfiguredAirbyteCatalog which is almost the same as AirbyteCatalog
            returned by discover(), but
        in addition, it's been configured in the UI! For each particular stream and field, there may have been provided
        with extra modifications such as: filtering streams and/or columns out, renaming some entities, etc
        :param state: When a Airbyte reads data from a source, it might need to keep a checkpoint cursor to resume
            replication in the future from that saved checkpoint.
            This is the object that is provided with state from previous runs and avoid replicating the entire set of
            data everytime.

        :return: A generator that produces a stream of AirbyteRecordMessage contained in AirbyteMessage object.
        """
        content_stream = "content"  # Example

        # try:
        #     peggle = Peggler()
        # except Exception as e:
        #     logger.error(f"Error when creating tester object: {e}")
        #     return
        age_count = 0
        logger.info(f"get this state: {state}")
        content_state = state.get("content")

        if content_state is not None:
            logger.info(f"content: {content_state}")
            age_count_state = state.get("content").get("age_count")
            logger.info(f"age_count: {age_count_state}")
            age_count = state.get("content").get("age_count")
            if age_count is None:
                age_count = 0
            logger.info(f"age_count in state: {age_count}")
        for i in range(10):
            content = dict()
            content["age"] = i + age_count
            content["created_at"] = generate_timestamp()
            content["name"] = {"name": "test", "surname": f"nya{i}"}

            yield AirbyteMessage(
                type=Type.RECORD,
                record=AirbyteRecordMessage(
                    stream=content_stream,
                    data=content,
                    emitted_at=datetime.now().timestamp() * 1000,
                ),
            )
        age_count += 10
        gen_state = generate_state(state, "content", {"age_count": age_count})
        logger.info(f"generated state: {gen_state}")
        yield gen_state
        # # generate a random number between 1 and 5
        # content = peggle.get_games()
        # logger.info(f"Found {len(content)} content(s) v1.0")
        # for c in content:
        #     c["videoData"]["uploadDate"] = c["videoData"]["uploadDate"][:-1]
        #     msg = AirbyteMessage(
        #         type=Type.RECORD,
        #         log=AirbyteLogMessage(level="INFO", message=f"Sending content {c.get('videoData').get('id')}"),
        #         record=AirbyteRecordMessage(stream=content_stream, data=c, emitted_at=int(datetime.now().timestamp()) * 1000),
        #     )
        #     logger.info(msg)
        #     yield msg
        # # yield generate_state(state, content_stream, {"content_count": len(content)})


if __name__ == "__main__":
    tester = Peggler()
    for c in tester.get_games():
        print(c)


def read_json(filepath):
    with open(filepath, "r") as f:
        return json.loads(f.read())


def generate_state(state: Dict[str, any], stream_name: any, data: any):
    state[stream_name] = data
    return AirbyteMessage(type=Type.STATE, state=AirbyteStateMessage(data=state))


def generate_timestamp():
    d = datetime.now().isoformat()
    s = f"{d}"
    s = s.split(".")[0]
    s += "+00:00"
    return s
